version: "3"

services:
  mongodb:
    container_name: "sample-api-mongodb"
    image: "mongo:4.2.6"
    volumes:
      - ./dbdata:/data/db
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "BookstoreDb"
